{
    "name": "Odoo Taxjar Connector",
    "version": "15.0.5",
    "category": "Account",
    "summary": "Compute sales tax automatically using TaxJar based on customer and warehouse address in United States.",
    "description": """
        TaxJar Integration,
        Odoo and TaxJar Integration,
        Odoo TaxJar Integration,
        TaxJar Odoo Integration,
        TaxJar and Odoo Integration,
        TeqStars Integration,
        Invoice Taxes,
        Refund Invoice Taxes,
        Refund Taxes,
        Account Taxes,
        Automatically Tax Calculation,
        Automatically Taxes Calculation,
        Automatically Tax Calculation,
        Automatically Taxes calculator,
        Nexus State,
        State Tax,
        State Taxes,
        Taxes State,
        Tax State,
        TaxJar Transaction,
        Sales tax Calculator,
        Sales taxes Calculator,
        Sales taxes calculation,
    """,
    "depends": ["delivery"],
    "data": [
        "security/ir_rule_views.xml",
        "data/ir_sequence_data.xml",
        "wizard/sync_multi_transaction_taxjar_view.xml",
        "views/taxjar_account_view.xml",
        "views/taxjar_category_view.xml",
        "security/ir.model.access.csv",
        "views/account_fiscal_postion_view.xml",
        "views/taxjar_tax_rate_view.xml",
        "views/product_category_view.xml",
        "views/product_template_view.xml",
        "views/res_partner_view.xml",
        "views/taxjar_logs_views.xml",
        "views/account_move_view.xml",
        "views/sale_order_view.xml",
    ],
    "images": ["static/description/taxjar_odoo.png"],
    "author": "Teqstars",
    "website": "https://teqstars.com",
    "support": "support@teqstars.com",
    "maintainer": "Teqstars",
    "demo": [],
    "license": "OPL-1",
    "live_test_url": "http://bit.ly/2qyponF",
    "auto_install": False,
    "installable": True,
    "application": True,
    "qweb": [],
    "price": "190.00",
    "currency": "EUR",
}
