{
    "name": "Inventory Generic Customisation",
    "summary": """
        Inventory Generic Customisation""",
    "description": """
    """,
    "author": "Bassam Infotech LLP",
    "website": "https://bassaminfotech.com",
    "support": "sales@bassaminfotech.com",
    "license": "OPL-1",
    "category": "Inventory",
    "version": "15.0.0.2",
    "depends": [
        "product",
        "stock",
        "bi_reason_code",
        "bi_shipping_zone",
        "delivery",
        "stock_account",
        "mail",
        "stock_picking_batch",
        "odoo_magento2_ept",
        "purchase",
        # "industry_fsm_sale",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/mail_security.xml",
        "security/cost_security.xml",
        "data/scheduler.xml",
        #"data/shipment_mail_template.xml",
        "views/product_breeder.xml",
        "views/product_category_view_inherit.xml",
        "views/product_flower_type.xml",
        "views/product_sex.xml",
        "views/product_size.xml",
        "views/product_template.xml",
        "views/scrap.xml",
        "views/stock_picking.xml",
        "views/stock_picking_type.xml",
        "views/shipping_method.xml",
        "views/stock_immediate_transfer_views.xml",
        "views/replenishment_view.xml",
        "views/product_attribute.xml",
        "views/stock_valuation.xml",
        "views/stock_move.xml",
        "views/stock_move_line.xml",
        #"views/res_config.xml",
        "views/res_country.xml",
        "views/stock_quant.xml",
        "views/update_stock_warehouse.xml",
        "views/action_cancel_picking.xml",
        "views/update_product_enable_action.xml",
        "views/res_company.xml",
        "views/product_product.xml",
        "views/product_tag.xml",
        "views/stock_picking_batch.xml",
        "views/purchase_order_line_view.xml",
        "views/res_partner.xml",
        "wizard/stock_return_picking.xml",
        "wizard/hold_wizard.xml",
        "wizard/cancel_wizard.xml",
        "wizard/update_tracking_ref.xml",
        "wizard/update_warehouse_wizard.xml",
        "wizard/stock_message_wizard.xml",
    ],
    "post_load": "post_load_hook",
}
