from . import product_product
from . import product_category
from . import product_breeder
from . import product_flower_type
from . import product_sex
from . import product_template
from . import product_size
from . import scrap
from . import stock_picking
from . import shipping_method
from . import stock_inmediate_transfer
from . import product_attribute
from . import stock_valuation
from . import stock_move
from . import stock_move_line
from . import res_config
from . import stock_replenishment
from . import stock_quant
from . import res_country
from . import res_company
from . import product_tag
from . import stock_picking_batch
from . import purchase_order
from . import res_partner
from . import magento_product_product
from . import product_pricelist
