from odoo import models


class GeneratemplateProductImport(models.AbstractModel):
    _name = "report.bi_barcode.generate_template_xlsx"
    _inherit = "report.report_xlsx.abstract"
    _description = "Export Template Line Import"

    def generate_xlsx_report(self, workbook, data, lines):
        worksheet = workbook.add_worksheet("Import Template")
        worksheet.set_column("A:A", 30)
        worksheet.set_column("B:B", 20)
        worksheet.set_column("C:C", 20)
        worksheet.set_column("D:D", 20)
        worksheet.set_column("E:E", 20)
        worksheet.set_column("F:F", 20)
        worksheet.set_column("G:G", 20)
        worksheet.set_column("H:H", 20)
        worksheet.set_column("I:I", 20)
        worksheet.set_column("J:J", 20)
        worksheet.set_column("K:K", 20)
        worksheet.set_column("L:L", 20)
        worksheet.set_column("M:M", 20)
        worksheet.set_column("N:N", 20)
        worksheet.set_column("O:O", 20)
        worksheet.set_column("P:P", 20)
        worksheet.set_column("Q:Q", 20)
        worksheet.set_column("R:R", 30)
        worksheet.set_column("S:S", 30)
        worksheet.set_column("T:T", 30)
        worksheet.set_column("U:U", 20)
        worksheet.set_column("V:V", 20)
        worksheet.set_column("W:W", 20)
        worksheet.set_column("X:X", 20)
        worksheet.set_column("Y:Y", 20)
        worksheet.set_column("Z:Z", 20)
        worksheet.set_column("AA:AA", 20)
        worksheet.set_column("AB:AB", 20)
        worksheet.set_column("AC:AC", 20)
        worksheet.set_column("AD:AD", 20)
        worksheet.set_column("AE:AE", 50)
        format_wrap_text = workbook.add_format({"text_wrap": "true"})
        worksheet.write("A1", "Product SKU", format_wrap_text)
        worksheet.write("B1", "Barcode", format_wrap_text)
        # worksheet.write("C1", "Wholesale Price", format_wrap_text)
        # worksheet.write("D1", "Last Cost", format_wrap_text)
        # worksheet.write("E1", "Retail GBP", format_wrap_text)
        # worksheet.write("F1", "Retail USD", format_wrap_text)
        # worksheet.write("G1", "Retail Default EUR", format_wrap_text)
        # worksheet.write("H1", "Retail Special EUR", format_wrap_text)
        # worksheet.write("I1", "Wsale Special EUR", format_wrap_text)

        # worksheet.write("J1", "Retail ZAR", format_wrap_text)
        # worksheet.write("K1", "Retail Special US", format_wrap_text)
        # worksheet.write("L1", "Retail Special ZA", format_wrap_text)
        # worksheet.write("M1", "Retail Special GBP", format_wrap_text)
        # worksheet.write("N1", "ZA Price", format_wrap_text)
        # worksheet.write("O1", "Wholesale US Price", format_wrap_text)

        worksheet.write("C1", "Case Quantity", format_wrap_text)
        worksheet.write("D1", "Out Of Stock", format_wrap_text)
        worksheet.write("E1", "Pending Discontinued", format_wrap_text)
        worksheet.write("F1", "Exclude from Replenishment", format_wrap_text)
        worksheet.write("G1", "Exclude from Pricelist", format_wrap_text)
        worksheet.write("H1", "Exclude from customers", format_wrap_text)
        worksheet.write("I1", "Back in Stock Date", format_wrap_text)
        worksheet.write("J1", "Supplier SKU", format_wrap_text)
        worksheet.write("K1", "PN US Two", format_wrap_text)
        worksheet.write("L1", "PhytoNation", format_wrap_text)
        worksheet.write("M1", "PN BR", format_wrap_text)
        worksheet.write("N1", "PN SA", format_wrap_text)
        worksheet.write("O1", "Out Of Stock Date", format_wrap_text)
        worksheet.write("P1", "Product Tags", format_wrap_text)
        worksheet.write("Q1", "Remove Product Tags", format_wrap_text)
        worksheet.write("R1", "Weight", format_wrap_text)
        worksheet.write("S1", "USA Replenishment Enable", format_wrap_text)
        worksheet.write("T1", "MALAGA Replenishment Enable", format_wrap_text)
        worksheet.write("U1", "UK Replenishment Enable", format_wrap_text)
        worksheet.write("V1", "HS Code", format_wrap_text)
        worksheet.write("W1", "Free Products", format_wrap_text)
